package voxy.friend.chat.otpless

enum class InitiateErrorType {
    INVALID_PARAMETERS,
    INVALID_PHONE,
    INVALID_PHONE_CHANNEL,
    INVALID_EMAIL,
    INVALID_EMAIL_CHANNEL,
    INVALID_PHONE_OR_EMAIL,
    INVALID_EXPIRY,
    INVALID_OTP_LENGTH,
    INVALID_APP_HASH,
    INVALID_REQUEST,
    INCORRECT_CHANNEL,
    UNAUTHORIZED,
    RATE_LIMIT,
    NETWORK_ERROR,
    UNKNOWN
}